// src/modules/counter/view/pages/Counter.svelte
<script>
  import { count, increment, decrement } from '../../application/services/useSvelteCounter';

  function incrementCount() {
    increment(1);
  }

  function decrementCount() {
    decrement(1);
  }
</script>

<h1>This is the Counter page</h1>
<p>The count is {$count}</p>
<button on:click={incrementCount}>+</button>
<button on:click={decrementCount}>-</button>

// src/modules/counter/view/pages/Counter.vue
<template>
  <h1>This is the Counter page</h1>
  <p>The count is {{ count }}</p>
  <button @click="increment(1)">+</button>
  <button @click="decrement(1)">-</button>
</template>

<script setup>
import useCounter from '../../application/services/useVueCounter'
const { count, increment, decrement } = useCounter()
</script>
